<a href="https://colab.research.google.com/github/yaseminekr/EmKa-Academy-Veri-bilimi/blob/main/NumPy_2_Al%C4%B1st%C4%B1rmalar__.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.

In [4]:
arr1 = np.arange(0,30)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
arr1.reshape(15,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

In [20]:
arr2 = np.random.rand(60)
arr2

array([0.33816899, 0.72298264, 0.03111685, 0.72799707, 0.47650118,
       0.69064585, 0.97152457, 0.21601435, 0.48474213, 0.59986617,
       0.88094127, 0.41713358, 0.78335008, 0.16532914, 0.31849057,
       0.84697854, 0.10575227, 0.99330232, 0.33264305, 0.88960372,
       0.64140262, 0.25217747, 0.48780688, 0.52017243, 0.28432687,
       0.90070066, 0.41865252, 0.07259008, 0.84113866, 0.65394338,
       0.2371181 , 0.53248298, 0.9795152 , 0.61959884, 0.04985393,
       0.33874234, 0.41547051, 0.78330051, 0.67541034, 0.43776875,
       0.99336703, 0.56808548, 0.71329365, 0.3531258 , 0.59649718,
       0.56215719, 0.49487618, 0.99574482, 0.26158654, 0.47134656,
       0.73900091, 0.23362803, 0.51986678, 0.52482899, 0.27437839,
       0.36528815, 0.07871645, 0.2385223 , 0.80390857, 0.42195446])

In [27]:
a = arr2.reshape((3,2,10))
a

array([[[0.33816899, 0.72298264, 0.03111685, 0.72799707, 0.47650118,
         0.69064585, 0.97152457, 0.21601435, 0.48474213, 0.59986617],
        [0.88094127, 0.41713358, 0.78335008, 0.16532914, 0.31849057,
         0.84697854, 0.10575227, 0.99330232, 0.33264305, 0.88960372]],

       [[0.64140262, 0.25217747, 0.48780688, 0.52017243, 0.28432687,
         0.90070066, 0.41865252, 0.07259008, 0.84113866, 0.65394338],
        [0.2371181 , 0.53248298, 0.9795152 , 0.61959884, 0.04985393,
         0.33874234, 0.41547051, 0.78330051, 0.67541034, 0.43776875]],

       [[0.99336703, 0.56808548, 0.71329365, 0.3531258 , 0.59649718,
         0.56215719, 0.49487618, 0.99574482, 0.26158654, 0.47134656],
        [0.73900091, 0.23362803, 0.51986678, 0.52482899, 0.27437839,
         0.36528815, 0.07871645, 0.2385223 , 0.80390857, 0.42195446]]])

In [28]:
a.ndim

3

In [29]:
a.shape

(3, 2, 10)

3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.


In [37]:
arr3 = np.arange(20).reshape(2,10)
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [47]:
b = arr3.reshape(-1)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [46]:
b.ndim

1

In [48]:
b.shape

(20,)

4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.


In [49]:
arr4 = np.arange(20).reshape(4,5)

In [50]:
for x in arr4:    # Yavaş
  for y in x:
    print(y)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [51]:
for x in np.nditer(arr3):    # Hızlı
  print(x)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
   1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.


In [54]:
arr5_1 = np.array([5,10,15,20,25,30])
arr5_2 = np.array([1,2,3,4,5,6])


In [55]:
arr5_1

array([ 5, 10, 15, 20, 25, 30])

In [57]:
arr5_2

array([1, 2, 3, 4, 5, 6])

In [59]:
arr5_1[2] + arr5_2[1]

17

In [60]:
arr5_1[2] * arr5_2[4]

75

In [61]:
arr5_1 / arr5_2

array([5., 5., 5., 5., 5., 5.])

In [62]:
arr5_1[4] - arr5_2[3]

21

6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.


In [63]:
arr6 = np.random.randint(0,100,10)
arr6

array([79, 73, 75,  6, 36, 56, 15,  4, 87, 38])

In [65]:
arr6.sum()

469

In [66]:
arr6.mean()

46.9

In [67]:
arr6.max()

87

In [69]:
arr6.var()

892.0899999999998

In [68]:
arr6.std()

29.86787571957537

7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.


In [70]:
arr7_1 = np.arange(0,20)
arr7_2 = np.arange(500,531)

In [71]:
np.concatenate([arr7_1,arr7_2])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.


In [87]:
arr8_1 = np.arange(15,51)
arr8_2 = np.arange(10,101)
birlesim = np.concatenate([arr8_1,arr8_2])
birlesim

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [88]:
birlesim[25:51] = 888
birlesim

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.


In [84]:
arr9_1 = np.arange(0,40).reshape(8,5)
arr9_2 = np.arange(320,360).reshape(8,5)

In [85]:
np.concatenate([arr9_1,arr9_2], axis=0) 


array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [320, 321, 322, 323, 324],
       [325, 326, 327, 328, 329],
       [330, 331, 332, 333, 334],
       [335, 336, 337, 338, 339],
       [340, 341, 342, 343, 344],
       [345, 346, 347, 348, 349],
       [350, 351, 352, 353, 354],
       [355, 356, 357, 358, 359]])

In [86]:
np.concatenate([arr9_1,arr9_2], axis=1) 


array([[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
       [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
       [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
       [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339],
       [ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
       [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
       [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
       [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]])

10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.


In [89]:
np.concatenate([arr9_1,arr9_2], axis=2) 

AxisError: ignored

In [93]:
np.stack([arr9_1,arr9_2], axis=2)

array([[[  0, 320],
        [  1, 321],
        [  2, 322],
        [  3, 323],
        [  4, 324]],

       [[  5, 325],
        [  6, 326],
        [  7, 327],
        [  8, 328],
        [  9, 329]],

       [[ 10, 330],
        [ 11, 331],
        [ 12, 332],
        [ 13, 333],
        [ 14, 334]],

       [[ 15, 335],
        [ 16, 336],
        [ 17, 337],
        [ 18, 338],
        [ 19, 339]],

       [[ 20, 340],
        [ 21, 341],
        [ 22, 342],
        [ 23, 343],
        [ 24, 344]],

       [[ 25, 345],
        [ 26, 346],
        [ 27, 347],
        [ 28, 348],
        [ 29, 349]],

       [[ 30, 350],
        [ 31, 351],
        [ 32, 352],
        [ 33, 353],
        [ 34, 354]],

       [[ 35, 355],
        [ 36, 356],
        [ 37, 357],
        [ 38, 358],
        [ 39, 359]]])

11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.


In [98]:
arr11 = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])

In [100]:
np.where(arr11 == 5)

(array([ 5, 13]),)

12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.


In [103]:
np.where(arr11 % 2 ==0)

(array([ 1,  3,  4,  6,  7,  9, 11]),)

13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.


In [104]:
np.where(arr11 > 4 )

(array([ 1,  2,  5,  9, 10, 11, 13]),)

14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.


In [105]:
np.where(arr11 % 5 ==0)

(array([ 1,  2,  5, 13]),)

15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin


In [110]:
arr15 = np.random.randint(85,101)
np.random.choice(arr15)

84

16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.


In [112]:
arr16 = np.random.randint(10, 100, (3, 3))
arr16

array([[84, 76, 55],
       [53, 85, 20],
       [34, 38, 37]])

In [115]:
arr16.shape

(3, 3)

17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.


In [114]:
arr17 = np.arange(35, 60) 
random_sayi = np.random.choice(arr17)  
random_sayi

52

18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.

In [118]:
arr18 = np.array([[3, 8, 10, 53, 3], [8, 10, 53, 3, 8]])
arr18

array([[ 3,  8, 10, 53,  3],
       [ 8, 10, 53,  3,  8]])