<a href="https://colab.research.google.com/github/yaseminekr/EmKa-Academy-Veri-bilimi/blob/main/NumPy_1_Al%C4%B1st%C4%B1rmalar_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin




In [11]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
arr3d.ndim

3

2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.

In [17]:
arr1 = np.arange(34,113,6)
arr1

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)


In [45]:
arr2 = np.linspace(50,500,91, dtype=int) # Endpoint dahil.
arr2

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

4) 100(10**2) ile 10000(10**5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.

In [21]:
arr3 = np.logspace(2,4,8)
arr3

array([  100.        ,   193.06977289,   372.75937203,   719.685673  ,
        1389.49549437,  2682.69579528,  5179.47467923, 10000.        ])

5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.

In [93]:
arr4 = np.arange(9)
matris = arr4.reshape((3, 3))
matris

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
matris.shape

(3, 3)

6) 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)

In [36]:
arr5 = np.zeros((6,6), dtype=int)
arr5

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)

In [25]:
arr6 = np.ones((4,4), dtype=int)
arr6

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)

In [33]:
arr7 = np.eye(8, dtype=int)
arr7

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

9) 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)

In [35]:
arr8 = np.zeros((5, 5), dtype=int)  
np.fill_diagonal(arr8, 3) 
arr8

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.

In [37]:
arr9 = np.random.rand(6)
arr9

array([0.51976692, 0.46015272, 0.39411519, 0.72802801, 0.4788051 ,
       0.25891355])

11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.

In [43]:
arr10 = np.random.randint(50,101, (5,2))
arr10

array([[58, 72],
       [53, 63],
       [52, 84],
       [55, 62],
       [61, 56]])

In [46]:
arr10.shape

(5, 2)

12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.

In [49]:
arr11 = np.random.randint(100,1000,(2,5,5))
arr11

array([[[680, 112, 547, 349, 745],
        [702, 934, 943, 464, 275],
        [628, 244, 954, 979, 424],
        [646, 122, 432, 571, 919],
        [312, 235, 229, 891, 711]],

       [[969, 246, 901, 862, 751],
        [704, 171, 540, 434, 718],
        [905, 709, 102, 130, 963],
        [692, 553, 194, 649, 527],
        [846, 218, 313, 453, 566]]])

In [50]:
arr11.ndim

3

In [51]:
arr11.shape

(2, 5, 5)

13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.

In [54]:
arr12 = np.random.randint(0,101,10)
arr12

array([ 97,  45,  98,  22,  67,  27,  64, 100,  67,   2])

In [57]:
arr12.max()

100

In [58]:
arr12.argmax()

7

In [60]:
arr12.min()

2

In [61]:
arr12.argmin()

9

14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.

In [64]:
arr13 = np.random.randint(300,501, (2,2,5))
arr13

array([[[399, 363, 436, 346, 418],
        [388, 306, 475, 308, 352]],

       [[418, 377, 430, 381, 384],
        [358, 459, 468, 329, 324]]])

In [73]:
arr13.max()

475

In [74]:

arr13[0,1,2]

475

In [67]:
arr13.min()

306

In [75]:
arr13[0,1,1]

306

15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

In [79]:
arr14 = np.arange(0,51,1)
arr14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [81]:
arr14[20:35] = 500
arr14

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])